### ISSUE TITLE
how to compile sass?

### ISSUE THREAD

**Issue by senlin** [corsonr/fredo#1]
Looked through the entire directory, but cannot find anything that compiles the sass files. Am I missing something?

**Comment by corsonr** [comment]
Here's how to compile sass:

https://github.com/corsonr/fredo/blob/master/assets/_sass/_Style.sass#L3

I haven't added anything related to NPM since I don't want to overcharge the whole package. I'll be adding a note in the readme how to compile sass.

**Comment by corsonr** [comment]
Added to readme.
