### ISSUE TITLE
remove wp reset query

### ISSUE THREAD

**Issue by jmau111** [corsonr/fredo#7]
I would use wp_reset_postdata() instead for this custom query https://github.com/corsonr/fredo/blob/master/index.php#L65 seems heavy to me here and here too https://github.com/corsonr/fredo/blob/master/single.php#L129

**Comment by corsonr** [comment]
Well spotted @jmau111! Fixed by https://github.com/corsonr/fredo/commit/40f60afb6370c3cce2aac727683c105b09eb4c6c
